### ISSUE TITLE
change Button style

### ISSUE THREAD

**Issue by RAMIROexe** [JuliTheProgrammer/OmniCloud-Project#5]
Change "Got to Dashboard" and "Get Started" button style -> Code unten ist noch nicht korrekt, muss noch verlinkt werden mit den Pages und so aber der style stimmt. Sollte eine Hover funktion mit Wolken im Button ergeben.

HTML: 
```html
<nav>
  <ul>
    <li>
      Go to Dashboard
      <span></span><span></span><span></span><span></span>
    </li><nav>
  <ul>
    <li>

      Get Started
      <span></span><span></span><span></span><span></span>
    </li>
``` 

CSS: 
```css
body {
    margin: 0;
    height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: black;
}

nav ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
}

nav ul li {
    --c: goldenrod;
    color: var(--c);
    font-size: 16px;
    border: 0.3em solid var(--c);
    border-radius: 0.5em;
    width: 12em;
    height: 3em;
    text-transform: uppercase;
    font-weight: bold;
    font-family: sans-serif;
    letter-spacing: 0.1em;
    text-align: center;
    line-height: 3em;
    position: relative;
    overflow: hidden;
    z-index: 1;
    transition: 0.5s;
    margin: 1em;
}

nav ul li span {
    position: absolute;
    width: 25%;
    height: 100%;
    background-color: var(--c);
    transform: translateY(150%);
    border-radius: 50%;
    left: calc((var(--n) - 1) * 25%);
    transition: 0.5s;
    transition-delay: calc((var(--n) - 1) * 0.1s);
    z-index: -1;
}

nav ul li:hover {
    color: black;
}

nav ul li:hover span {
    transform: translateY(0) scale(2);
}

nav ul li span:nth-child(1) {
    --n: 1;
}

nav ul li span:nth-child(2) {
    --n: 2;
}

nav ul li span:nth-child(3) {
    --n: 3;
}

nav ul li span:nth-child(4) {
    --n: 4;
}
```
